### ISSUE TITLE
ImportError: No module named parse报错

### ISSUE THREAD

**Issue by DmuMenDuo** [showzeng/2018_code_calendar_wallpaper_Linux#2]
`python calendar.py` 这样子启动的话需要把 
`from urllib.parse import urlparse`
换成
`from urlparse import urlparse`
查了一下 好像这里py3 py2是不兼容的

**Comment by ZoeyWoohoo** [comment]
@DmuMenDuo 是的，依赖里指明了 Python3，现在都转向 3 了，如果是 2 的话需要自己去修改兼容。

**Comment by DmuMenDuo** [comment]
@showzeng enen close 了 谢谢
